background              #10140f
foreground              #e0e4da
cursor                  #a2d399
cursor_text_color       #0c390e
selection_background    #255023
selection_foreground    #bdf0b3
url_color               #a0cfd3
active_border_color     #a2d399
inactive_border_color   #42493f

color0   #272b25
color8   #8c9388
color1   #ffb4a4
color9   #ffb4a4
color2   #a7d394
color10  #a7d394
color3   #dbc66e
color11  #dbc66e
color4   #a2d399
color12  #a2d399
color5   #a0cfd3
color13  #a0cfd3
color6   #baccb3
color14  #baccb3
color7   #c2c8bd
color15  #e0e4da
